### ISSUE TITLE
Bee 1.5.0

### ISSUE THREAD

**Issue by joelmiguelvalente** [Moxtrip69/Bee-Framework#1]
Lo he probado con PHP 8.1.6
En esta línea tuve problemas
https://github.com/Moxtrip69/Bee-Framework/blob/1.5.0/app/functions/bee_core_functions.php#L420

Mensaje de error
```
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in C:\xampp\htdocs\bee\app\functions\bee_core_functions.php on line 420
```

La solución que le aplique y no sé si será correcta, fue reemplazar **FILTER_SANITIZE_STRING** por **FILTER_UNSAFE_RAW**

Según PHP dice: [Filtros de saneamiento](https://www.php.net/manual/es/filter.filters.sanitize.php)
`No hace nada, opcionalmente eliminar o codificar caracteres. Este filtro es un alias de FILTER_DEFAULT.`

**Comment by Moxtrip69** [comment]
Solucionado, muchas gracias!
