### ISSUE TITLE
Aqui esta equivocada la variabley no funciona la funcin deberia ser $get_data

### ISSUE THREAD

**Issue by YOESCO** [Moxtrip69/Bee-Framework#2]
https://github.com/Moxtrip69/Bee-Framework/blob/fceab9936b056d2de22298b0d6570946d8751705/app/functions/bee_core_functions.php#L963

Hay un error en la funcion que hace que no funcione a la hora de verificar el token ya que la variable debe ser $get_data en lugar de: $posted_data

 if(empty($required_params) || empty($posted_data))

**Comment by Moxtrip69** [comment]
> https://github.com/Moxtrip69/Bee-Framework/blob/fceab9936b056d2de22298b0d6570946d8751705/app/functions/bee_core_functions.php#L963
> 
> Hay un error en la funcion que hace que no funcione a la hora de verificar el token ya que la variable debe ser $get_data en lugar de: $posted_data
> 
> if(empty($required_params) || empty($posted_data))

Solucionado muchas gracias!
